# Generated by Django 4.2.9 on 2024-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='36250f', max_length=6),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
