# Generated by Django 4.2.9 on 2024-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_w',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_w',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='visit_duration',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='8e95c0', max_length=6),
        ),
    ]
