# Generated by Django 4.2.9 on 2024-05-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='The_right_DOC.doctor'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e54ec3', max_length=6),
        ),
    ]
