# Generated by Django 4.2.9 on 2024-04-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0002_rename_full_name_doctor_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f1dc50', max_length=6),
        ),
    ]
