# Generated by Django 4.2.9 on 2024-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0002_doctor_end_w_doctor_start_w_doctor_visit_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='f14ae9', max_length=6),
        ),
    ]
