# Generated by Django 4.2.10 on 2024-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0003_rename_markers_marker_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_w',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_w',
            field=models.TimeField(default='6:00:00'),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1645c4', max_length=6),
        ),
    ]
