# Generated by Django 4.2.9 on 2024-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0003_reservation_description_alter_otptoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='132bca', max_length=6),
        ),
    ]
