# Generated by Django 4.2.9 on 2024-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0004_alter_doctor_specialty_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e894d6', max_length=6),
        ),
    ]
