# Generated by Django 4.2.9 on 2024-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0004_alter_doctor_password_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='506093', max_length=6),
        ),
    ]
