# Generated by Django 4.2.9 on 2024-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_right_DOC', '0006_alter_otptoken_otp_code_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='9b8f38', max_length=6),
        ),
    ]
